### ISSUE TITLE
Program doesn't work when using Google Maps API-key

### ISSUE THREAD

**Issue by m0ng3y** [algoni/PogoBot-Telegram#1]
In this example I have one user which has Pidgey on its list.

The problem looks like this in the console:
info: A wild Pidgey appeared! Disappear time 1470693470
Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"IMAGE_PROCESS_FAILED"}
    at C:\PogoBot-Telegram-master\node_modules\node-telegram-bot-api\lib\telegram.js:186:17
    at tryCatcher (C:\PogoBot-Telegram-master\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\PogoBot-Telegram-master\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\PogoBot-Telegram-master\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\PogoBot-Telegram-master\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\PogoBot-Telegram-master\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\PogoBot-Telegram-master\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](C:PogoBot-Telegram-masternode_modulesnode-telegram-bot-apinode_modulesrequest-promisenode_modulesbluebirdjsmainasync.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:383:17)

Obviously I'm not getting any messages from my bot.

I'm using the same Google Maps API-key as I'm using with my map. The strange thing is that if I leave the API-key empty, the error is gone and the bot sends me the correct message. However I'd like to use the API-key for my requests.

I don't know much about programming, but Googling around the error message it shows that it has something to do with the text encoding or something?

**Comment by s-hirvonen** [comment]
Hmm... When it fails, do you still get the image saved in `.tmp/`?

**Comment by m0ng3y** [comment]
Figured it out.

The .png-files were actually just plain text inside which told me that my API-key was not good for the request.

Had to go and enable "Google Static Maps API" for the key also, I don't think it's needed on the PokemonGoMap itself? At least my map has been working without it.

Everything seems to work great now, thanks for a fantastic bot!

**Comment by s-hirvonen** [comment]
Oh yeah! My bad, forgot exactly what steps to take as I was hacking this together. I'll update the readme. Thanks!
