### ISSUE TITLE
Bot quits with "Request failed with code 500"

### ISSUE THREAD

**Issue by samwiseg0** [algoni/PogoBot-Telegram#26]
The bot runs for a while and then quits unexpectedly with the following error. The google Maps API is correct and is working up until the bot crashes with this error.

Anything I can do to debug?

```
error: Request failed with code 500
error: Make sure you have Static Maps API enabled on your key.

Error: Failed to get map image from Google Maps API.
    at Request._callback (/webapps/PogoBot-Telegram/src/notificationManager.js:65:23)
    at Request.self.callback (/webapps/PogoBot-Telegram/node_modules/request/request.js:187:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/webapps/PogoBot-Telegram/node_modules/request/request.js:1044:10)
    at Request.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (/webapps/PogoBot-Telegram/node_modules/request/request.js:965:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:458:13)
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by samwiseg0** [comment]
Thought I was using the develop branch but was not. Things seem more stable now
