### ISSUE TITLE
IMAGE_PROCESS_FAILED

### ISSUE THREAD

**Issue by gmkbenjamin** [algoni/PogoBot-Telegram#3]
Issue:
info: A wild Pinsir appeared! Disappear time 1470729339
info: A wild Weedle appeared! Disappear time 1470729442
Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"IMAGE_PROCESS_FAILED"}
    at C:\PogoBot-Telegram\node_modules\node-telegram-bot-api\lib\telegram.js:186:17
    at tryCatcher (C:\PogoBot-Telegram\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\PogoBot-Telegram\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\PogoBot-Telegram\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\PogoBot-Telegram\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\PogoBot-Telegram\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\PogoBot-Telegram\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](C:PogoBot-Telegramnode_modulesnode-telegram-bot-apinode_modulesrequest-promisenode_modulesbluebirdjsmainasync.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:383:17)
Unhandled rejection Error: 400 {"ok":false,"error_code":400,"description":"IMAGE_PROCESS_FAILED"}
    at C:\PogoBot-Telegram\node_modules\node-telegram-bot-api\lib\telegram.js:186:17
    at tryCatcher (C:\PogoBot-Telegram\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\PogoBot-Telegram\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\PogoBot-Telegram\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\PogoBot-Telegram\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\PogoBot-Telegram\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\PogoBot-Telegram\node_modules\node-telegram-bot-api\node_modules\request-promise\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](C:PogoBot-Telegramnode_modulesnode-telegram-bot-apinode_modulesrequest-promisenode_modulesbluebirdjsmainasync.js:15:14)
    at processImmediate [as _immediateCallback](timers.js:383:17)

OS: Windows 10 Pro 64bit
Commit: 6148bd5

**Comment by RiberoD07** [comment]
this had to do with how images were saved locally, this specific error should be fixed as of commit: 38db8c0
