### ISSUE TITLE
Unsupported Buffer File Type

### ISSUE THREAD

**Issue by RiberoD07** [algoni/PogoBot-Telegram#5]
did nothing special, git reset --hard git pull config file was the same, started mongod.exe and npm start
activated the user by typing /start in telegram.
only throws the error when a pokemon that is on my watchlist appears
windows 10 64-bit
happens on the latest commit of both master and develop branch

C:\Users\Daniel\Desktop\telegrambot\PogoBot-Telegram\node_modules\node-telegram-bot-api\lib\telegram.js:362
          throw new Error('Unsupported Buffer file type');
          ^

Error: Unsupported Buffer file type
    at TelegramBot._formatSendData (C:\Users\Daniel\Desktop\telegrambot\PogoBot-Telegram\node_modules\node-telegram-bot-api\lib\telegram.js:362:17)
    at TelegramBot.sendPhoto (C:\Users\Daniel\Desktop\telegrambot\PogoBot-Telegram\node_modules\node-telegram-bot-api\lib\telegram.js:407:26)
    at C:\Users\Daniel\Desktop\telegrambot\PogoBot-Telegram\src\bot.js:29:17
    at arrayEach (C:\Users\Daniel\Desktop\telegrambot\PogoBot-Telegram\node_modules\lodash\lodash.js:485:11)
    at Function.forEach (C:\Users\Daniel\Desktop\telegrambot\PogoBot-Telegram\node_modules\lodash\lodash.js:8882:14)
    at Object.exports.sendPhotoNotification (C:\Users\Daniel\Desktop\telegrambot\PogoBot-Telegram\src\bot.js:28:11)
    at Request._callback (C:\Users\Daniel\Desktop\telegrambot\PogoBot-Telegram\src\notificationManager.js:47:17)
    at Request.self.callback (C:\Users\Daniel\Desktop\telegrambot\PogoBot-Telegram\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\Daniel\Desktop\telegrambot\PogoBot-Telegram\node_modules\request\request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\Daniel\Desktop\telegrambot\PogoBot-Telegram\node_modules\request\request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by s-hirvonen** [comment]
Got this reproduced now.

Go to https://console.developers.google.com/apis/library and make sure the Google Static Maps API is enabled (allows fetching maps as .png images).
